### ISSUE TITLE
Program crash on exporting to .csv if end time of row is before the log started

### ISSUE THREAD

**Issue by scottie4444** [fredemmott/XRFrameTools#28]
[iRacingSim64DX11 2024-12-23 13-05-38.1515691 UTC.zip](https://github.com/user-attachments/files/18230132/iRacingSim64DX11.2024-12-23.13-05-38.1515691.UTC.zip)

When trying to export the attached log file to .csv with less than 3 frames per row as an option, the program crashes and only exports a .csv with the headers and no data included. 3 or more frames per row works as expected.

**Comment by fredemmott** [comment]
The log starts with the current time in both a reboot-specific counter, and a real date/time. When converting to CSV calculates the 'human readable' time by comparing the frame end time to the reboot-specific counter.

Problem is:
- to help catch bugs on my end, it checks that durations are never negative, i.e. the rows' submission time is after the log start time
- writing to the binary log happens in a separate thread to the game loop; on heavily loaded systems, the log *can* start after the frames. In your case, the first frame finishes 1.5ms before the log starts

**Comment by fredemmott** [comment]
You can get the fix from the `build64` link at the bottom of https://github.com/fredemmott/XRFrameTools/actions/runs/12483295682

The new `XRFrameTools.exe` and `binlog-to-csv.exe` (a command-line converter for bulk conversions) are inside the `bin` subfolder

**ONLY USE THESE EXE FILES TO CONVERT YOUR CSV FILES** - for iRacing in particular:
- *do not* use the `*UNSIGNED.msi` file from that link
- *do not* replace any DLLs in your XRFrameTools installation with the newer ones
- If you use the 'live data' feature, don't replace the exe files either - just run them by themselves. Only use the new exes for producing CSV files, just running them from wherever you extract them

Making XRFrameTools compatible with anti-cheat software requires manual steps for each release, so automated builds are *not* compatible with games that use iRacing.
- if you update the dlls, you will be unable to start iRacing
- the new exes are capable of procesing the old binary logs, but are not capable of showing live data from the old dlls
